Add version property
NetOfficeFw/vbamc pull request #7
Opened 2023-06-19 13:30 UTC by m-kovac

Add version property for VbaCompiler and use it when compiling macro file as macro template package **version** property.

2023-06-19 14:12 UTC, DominikPalo approved these changes

2023-06-21 09:27 UTC, jozefizso requested changes

2023-06-21 09:27 UTC, jozefizso commented on src/VbaCompiler/VbaCompiler.cs
> +        public string ProjectVersion { get; set; } = "1";
The project version attribute should be optional.

2023-06-21 10:16 UTC, jozefizso approved these changes

2023-07-06 16:07 UTC, merged